# Generated by Django 4.1 on 2022-08-30 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='solution',
            field=models.TextField(max_length=10000),
        ),
    ]
